# Generated by Django 2.2.2 on 2019-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190614_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
