# Generated by Django 2.2.2 on 2019-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('featured_on_index', models.BooleanField()),
                ('featured_on_about', models.BooleanField()),
            ],
        ),
    ]
