# Generated by Django 2.2.2 on 2019-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20190620_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slider_slide_1_subheading',
            field=models.CharField(max_length=100, verbose_name='Slider Slide 1 Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_2_subheading',
            field=models.CharField(max_length=100, verbose_name='Slider Slide 2 Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_3_subheading',
            field=models.CharField(max_length=100, verbose_name='Slider Slide 2 Unterüberschrift'),
        ),
    ]
