# Generated by Django 2.2.2 on 2019-06-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20190624_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis'),
        ),
    ]
