# Generated by Django 2.2.2 on 2019-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20190701_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='unit',
            field=models.CharField(choices=[('NONE', 'Keine'), ('L', 'Liter'), ('ML', 'Milliliter'), ('CL', 'Centiliter')], default='NONE', max_length=20, verbose_name='Einheit auf der Karte'),
        ),
    ]
