# Generated by Django 2.2.2 on 2019-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20190701_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuppq',
            name='content',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='menuppq',
            name='unit',
            field=models.CharField(choices=[('NONE', 'Keine'), ('L', 'Liter'), ('ML', 'Milliliter'), ('CL', 'Centiliter')], default='NONE', max_length=20, verbose_name='Einheit'),
        ),
    ]
