# Generated by Django 2.2.2 on 2019-07-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20190719_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='hello_section_text_small',
            new_name='hello_section_small_text',
        ),
    ]
