# Generated by Django 2.2.2 on 2019-07-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20190719_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='about_page_big_heading',
            new_name='about_page_team_section_big_heading',
        ),
    ]
