# Generated by Django 2.2.2 on 2019-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20190719_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='about_page_about_section_big_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Über-uns-Section große Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_about_section_small_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Über-uns-Section kleine Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_gallery_section_big_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Galerie-Section große Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_gallery_section_small_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Galerie-Section kleine Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_to_contact_section_button',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Zum-Kontakt-Section Button Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_to_contact_section_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite Zum-Kontakt-Section Überschrift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_about_text',
            field=models.TextField(verbose_name='Über-uns-Seite Über-uns-Section Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_team_section_big_heading',
            field=models.CharField(max_length=100, verbose_name='Über-uns-Seite Team-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_team_section_small_heading',
            field=models.CharField(max_length=100, verbose_name='Über-uns-Seite Team-Section kleine Überschrift'),
        ),
    ]
