# Generated by Django 2.2.2 on 2019-07-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20190719_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='about_page_about_text',
            new_name='about_page_about_section_text',
        ),
    ]
