# Generated by Django 2.2.2 on 2019-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20190719_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Galerie Bild', 'verbose_name_plural': 'Galerie Bilder'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='featured_on_about',
            field=models.BooleanField(help_text='Auf der Über uns Seite in der Gallerie anzeigen? Maximal 5.', verbose_name='Featured auf der Über uns Seite'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='featured_on_index',
            field=models.BooleanField(help_text='Auf der Startseite in der Gallerie anzeigen? Maximal 5.', verbose_name='Featured auf der Startseite'),
        ),
    ]
