# Generated by Django 2.2.2 on 2019-07-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20190719_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Kann leer bleiben. Uhrzeit kann weggelassen werden.\nBeispiel Datum: 19.07.2019\nBeispiel Uhrzeit: 14:49:00', null=True, verbose_name='Datum und Uhrzeit'),
        ),
    ]
