# Generated by Django 2.2.2 on 2019-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20190725_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_about_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Über-uns-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_about_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Über-uns-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_about_section_text',
            field=models.TextField(blank=True, verbose_name='Über-uns-Seite Über-uns-Section Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_gallery_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Galerie-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_gallery_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Galerie-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_team_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Team-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_team_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Team-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_to_contact_section_button',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Zum-Kontakt-Section Button Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='about_page_to_contact_section_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Über-uns-Seite Zum-Kontakt-Section Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='location',
            name='article_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Artikel-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='article_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Artikel-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='events_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Events-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='events_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Events-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gallery_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Galerie-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gallery_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Galerie-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hello_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hallo-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hello_section_big_text',
            field=models.TextField(blank=True, verbose_name='Hallo-Section Fetter Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hello_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hallo-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hello_section_small_text',
            field=models.TextField(blank=True, verbose_name='Hallo-Section Normaler Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu_page_bottom_section_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Menü-Seite Untere-Section Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu_page_bottom_section_subheading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Menü-Seite Untere-Section Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu_section_big_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Menu-Section große Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu_section_small_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Menu-Section kleine Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_hours',
            field=models.TextField(blank=True, verbose_name='Öffnungszeiten'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_1_heading',
            field=models.TextField(blank=True, help_text='2 Zeilen empfohlen.', verbose_name='Slider-Slide-1 Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_1_subheading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slider-Slide-1 Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_2_heading',
            field=models.TextField(blank=True, help_text='2 Zeilen empfohlen.', verbose_name='Slider-Slide-2 Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_2_subheading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slider-Slide-2 Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_3_heading',
            field=models.TextField(blank=True, help_text='2 Zeilen empfohlen.', verbose_name='Slider-Slide-3 Überschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slider_slide_3_subheading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slider-Slide-3 Unterüberschrift'),
        ),
        migrations.AlterField(
            model_name='location',
            name='to_contact_section_button',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zum-Kontakt-Section Button Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='to_contact_section_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zum-Kontakt-Section Überschrift'),
        ),
    ]
