# Generated by Django 2.2.2 on 2019-08-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_menucategory_category1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['name'], 'verbose_name': 'Speisekarte Kategorie', 'verbose_name_plural': 'Speisekarte Kategorien'},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='eat_or_drink',
        ),
    ]
