# Generated by Django 2.2.2 on 2019-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20190808_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
