# Generated by Django 2.2.2 on 2019-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_menucategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Speisekarte Kategorie', 'verbose_name_plural': 'Speisekarte Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='menucategory1',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Speisekarte Kategorie 1', 'verbose_name_plural': 'Speisekarte Kategorien 1'},
        ),
        migrations.AddField(
            model_name='menucategory1',
            name='order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
