# Generated by Django 2.2.2 on 2019-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20190808_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-order', 'name'], 'verbose_name': 'Speisekarte Kategorie 2', 'verbose_name_plural': 'Speisekarte Kategorien 2'},
        ),
        migrations.AlterModelOptions(
            name='menucategory1',
            options={'ordering': ['-order', 'name'], 'verbose_name': 'Speisekarte Kategorie 1', 'verbose_name_plural': 'Speisekarte Kategorien 1'},
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_mail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kontakt E-Mail'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kontakt Telefon'),
        ),
    ]
