# Generated by Django 2.2.2 on 2019-08-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_auto_20190809_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='content.MenuCategory1', verbose_name='Kategorie 1'),
        ),
    ]
