# Generated by Django 2.2.2 on 2019-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20190809_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('image', models.ImageField(upload_to='members/', verbose_name='Bild')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Je höher, desto weiter oben.', verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Teammitglieder',
                'ordering': ['-order'],
            },
        ),
    ]
