# Generated by Django 2.2.2 on 2019-08-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_menucategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_category/', verbose_name='Bild'),
        ),
    ]
