# Generated by Django 2.2.2 on 2020-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_location_togo_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='togo_menu',
            field=models.FileField(upload_to='togo/', verbose_name='Togo Karte'),
        ),
    ]
