# Generated by Django 2.2.16 on 2020-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_auto_20200828_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsnippet',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
