# Generated by Django 2.2.16 on 2020-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_auto_20201126_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['key'], 'verbose_name': 'Einstellung', 'verbose_name_plural': 'Einstellungen'},
        ),
    ]
