# Generated by Django 4.0.2 on 2022-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_job_delete_member_remove_menucategory_category1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(help_text='Beispiel Datum: 19.07.2019', verbose_name='Datum'),
        ),
    ]
