# Generated by Django 4.0.2 on 2022-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_article_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Anzeigen'),
        ),
    ]
