# Generated by Django 2.2.2 on 2019-06-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='thecornerhouse', max_length=50, unique=True)),
                ('opening_hours', models.TextField()),
                ('contact_mail', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('about_text', models.TextField()),
            ],
        ),
    ]
