# Generated by Django 2.2.2 on 2019-06-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_business'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Location',
        ),
    ]
