# Generated by Django 2.2.2 on 2019-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='featured',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
