# Generated by Django 2.2.2 on 2019-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20190615_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slider_slide_1_heading',
            field=models.TextField(default='', verbose_name='Slider Slide 1 Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slider_slide_1_subheading',
            field=models.TextField(default='', verbose_name='Slider Slide 1 Unterüberschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slider_slide_2_heading',
            field=models.TextField(default='', verbose_name='Slider Slide 2 Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slider_slide_2_subheading',
            field=models.TextField(default='', verbose_name='Slider Slide 2 Unterüberschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slider_slide_3_heading',
            field=models.TextField(default='', verbose_name='Slider Slide 3 Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='slider_slide_3_subheading',
            field=models.TextField(default='', verbose_name='Slider Slide 2 Unterüberschrift'),
            preserve_default=False,
        ),
    ]
