# Generated by Django 2.2.2 on 2019-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20190620_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='eat_or_drink',
            field=models.CharField(choices=[('EAT', 'Essen'), ('DRINK', 'Trinken')], default='EAT', max_length=20),
        ),
    ]
