# Generated by Django 2.2.2 on 2019-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_menucategory_eat_or_drink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['eat_or_drink', 'name'], 'verbose_name': 'Speisekarte Kategorie', 'verbose_name_plural': 'Speisekarte Kategorien'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='featured_on_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='eat_or_drink',
            field=models.CharField(choices=[('EAT', 'Essen'), ('DRINK', 'Trinken')], default='EAT', max_length=20, verbose_name='Essen oder Trinken'),
        ),
    ]
