# Generated by Django 2.2.2 on 2019-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20190624_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
