# Generated by Django 2.2.2 on 2019-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_menuentry_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentry',
            name='price',
        ),
        migrations.AddField(
            model_name='menuentry',
            name='content1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Inhalt Rechts'),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis Rechts'),
        ),
        migrations.AddField(
            model_name='menuentry',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis Links'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='content2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Inhalt Links'),
        ),
    ]
