# Generated by Django 2.2.2 on 2019-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20190701_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='content1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inhalt rechts muss größer sein als Inhalt links.', max_digits=5, verbose_name='Inhalt rechts'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='content2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Inhalt links'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis rechts'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preis links'),
        ),
    ]
