# Generated by Django 2.2.2 on 2019-07-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20190701_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuentry',
            old_name='ppq',
            new_name='ppqs',
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_entries', to='content.MenuCategory', verbose_name='Kategorie'),
        ),
    ]
