# Generated by Django 2.2.2 on 2019-07-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20190701_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuppq',
            options={'ordering': ['unit', 'content', 'price'], 'verbose_name': 'Speisekarte Preise', 'verbose_name_plural': 'Speisekarte Preise'},
        ),
    ]
