# Generated by Django 2.2.2 on 2019-07-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20190701_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Nummer')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Speisekarte Zusatzstoff',
                'verbose_name_plural': 'Speisekarte Zusatzstoffe',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='menuentry',
            name='additives',
            field=models.ManyToManyField(related_name='menu_entries', to='content.MenuAdditive'),
        ),
    ]
