# Generated by Django 2.2.2 on 2019-07-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20190719_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='table_reserve_heading',
            new_name='to_contact_section_heading',
        ),
    ]
