# Generated by Django 2.2.2 on 2019-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20190719_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='about_text',
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_about_text',
            field=models.TextField(default='', verbose_name='Über-uns-Seite Über uns Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_big_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite große Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='about_page_small_heading',
            field=models.CharField(default='', max_length=100, verbose_name='Über-uns-Seite kleine Überschrift'),
            preserve_default=False,
        ),
    ]
