# Generated by Django 2.2.2 on 2019-07-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20190719_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='about_page_small_heading',
            new_name='about_page_team_section_small_heading',
        ),
    ]
