# Generated by Django 2.2.2 on 2019-07-19 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20190719_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Beispiel Datum: 19.07.2019<br>Beispiel Uhrzeit: 14:49:00', null=True, verbose_name='Datum und Uhrzeit'),
        ),
    ]
