# Generated by Django 2.2.2 on 2019-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20190719_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='additives',
            field=models.ManyToManyField(blank=True, related_name='menu_entries', to='content.MenuAdditive'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='ppqs',
            field=models.ManyToManyField(blank=True, related_name='menu_entries', to='content.MenuPPQ'),
        ),
    ]
