# Generated by Django 2.2.2 on 2019-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20190808_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Speisekarte Kategorie 1',
                'verbose_name_plural': 'Speisekarte Kategorien 1',
                'ordering': ['name'],
            },
        ),
    ]
