# Generated by Django 2.2.2 on 2019-08-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20190808_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Speisekarte Kategorie 2', 'verbose_name_plural': 'Speisekarte Kategorien 2'},
        ),
    ]
