# Generated by Django 2.2.2 on 2020-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_auto_20190826_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='togo_menu',
            field=models.ImageField(default='', upload_to='togo/', verbose_name='Togo Karte'),
            preserve_default=False,
        ),
    ]
