# Generated by Django 2.2.16 on 2020-11-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_auto_20200918_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
