# Generated by Django 2.2.16 on 2020-11-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_auto_20201126_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
