# Generated by Django 2.2.16 on 2020-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_auto_20201126_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Setting',
        ),
    ]
