# Generated by Django 2.2.16 on 2020-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_auto_20201126_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
