# Generated by Django 2.2.16 on 2020-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20201126_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='togo_menu',
            new_name='file',
        ),
    ]
