# Generated by Django 2.2.16 on 2020-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_auto_20201126_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='file',
            field=models.FileField(upload_to='togo/', verbose_name='Datei'),
        ),
    ]
