# Generated by Django 2.2.16 on 2020-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_auto_20201126_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='file',
            field=models.FileField(upload_to='setting-files/', verbose_name='Datei'),
        ),
    ]
