# Generated by Django 2.2.2 on 2019-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('location', models.CharField(choices=[('HEAD', 'Header'), ('BODY', 'Body')], max_length=200)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('title_tag', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=10000)),
            ],
        ),
    ]
