# Generated by Django 2.2.2 on 2019-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcode',
            name='name',
            field=models.CharField(default='Facebook Pixel', max_length=200),
            preserve_default=False,
        ),
    ]
