# Generated by Django 2.2.2 on 2019-06-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customcode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcode',
            name='location',
            field=models.CharField(choices=[('HEAD', 'Head'), ('BODY', 'Body')], max_length=200),
        ),
    ]
