# Generated by Django 2.2.2 on 2019-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190615_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcode',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
