# Generated by Django 2.2.2 on 2019-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190615_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Wie soll die Seite in der URL-Leiste erscheinen oder heißen?', unique=True, verbose_name='Slug')),
                ('shown_in_footer', models.BooleanField(help_text='Im Footer den Link zur Seite anzeigen?', verbose_name='Angezeigt im Footer')),
                ('shown_in_navigation', models.BooleanField(help_text='In der Navigation anzeigen?', verbose_name='Angezeigt in der Navigation')),
                ('activate_html', models.BooleanField(help_text='Soll der Inhalt als Html Code gerendert werden?', verbose_name='Html Code aktiviert')),
                ('content', models.TextField(verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Statische Seite',
                'verbose_name_plural': 'Statische Seiten',
            },
        ),
        migrations.AlterModelOptions(
            name='customcode',
            options={'verbose_name': 'Custom Code', 'verbose_name_plural': 'Custom Codes'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo', 'verbose_name_plural': 'Seos'},
        ),
        migrations.AlterField(
            model_name='customcode',
            name='code',
            field=models.TextField(help_text='Der Code wird nicht validiert und sollte richtig sein.', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='customcode',
            name='location',
            field=models.CharField(choices=[('HEAD', 'Head'), ('BODY', 'Body')], help_text='Wo soll der Code eingebunden werden?', max_length=200, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='customcode',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customcode',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(verbose_name='Meta Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_tag',
            field=models.CharField(max_length=200, verbose_name='Titel Tag'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
