# Generated by Django 2.2.2 on 2019-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190615_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticpage',
            old_name='activate_html',
            new_name='html_activated',
        ),
    ]
