# Generated by Django 2.2.16 on 2021-10-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formular_titel', models.CharField(default='Tisch reservieren', max_length=200, verbose_name='Formular / Titel')),
                ('formular_hinweise', models.TextField(default='Hinweise: Reservierungen für den gleichen Tag sind nur bis 16 Uhr online möglich, danach bitte in der Bar anrufen. Die Reservierung wird erst nach der Bestätigung durch uns gültig. Bitte kontrolliert Euer E-Mail Postfach. Hochtische mit Barhockern werden von uns als normale Tische behandelt. Eine Reservierung ist nur entweder im (Winter-)Biergarten oder in der Bar möglich.', verbose_name='Formular / Hinweise')),
                ('formular_biergarten', models.CharField(default='Biergarten', max_length=100, verbose_name='Formular / Ort / Biergarten')),
                ('formular_biergarten_verfuegbar', models.BooleanField(default=True, verbose_name='Formular / Ort / Biergarten auswählbar')),
                ('formular_bar_verfuegbar', models.BooleanField(default=True, verbose_name='Formular / Ort / Bar auswählbar')),
                ('formular_button', models.CharField(default='Jetzt reservieren', max_length=100, verbose_name='Formular / Bar')),
                ('formular_hinweis', models.TextField(default='Die Reservierung wird erst nach der Bestätigung durch uns gültig. Bitte kontrolliert Euer E-Mail Postfach.', verbose_name='Formular / Hinweis')),
            ],
            options={
                'verbose_name': 'Kontakt',
            },
        ),
    ]
