# Generated by Django 4.0.2 on 2022-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_pre', models.CharField(default='Jobs', max_length=200, verbose_name='Start / Vortitel')),
                ('start_title', models.CharField(default='Wir suchen', max_length=200, verbose_name='Start / Titel')),
            ],
            options={
                'verbose_name': 'Jobs',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
