# Generated by Django 4.0.2 on 2022-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_jobs_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobs_empty',
            field=models.TextField(default='', verbose_name='Jobs / Keine Jobs ausgeschrieben'),
            preserve_default=False,
        ),
    ]
