# Generated by Django 4.0.2 on 2022-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_jobs_jobs_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobs_button',
            field=models.CharField(default='Informationen anfordern', max_length=200, verbose_name='Jobs / Button'),
        ),
    ]
