# Generated by Django 4.0.2 on 2022-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_jobs_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='form_button',
            field=models.CharField(default='Absenden', max_length=200, verbose_name='Formular / Button'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='form_title',
            field=models.CharField(default='Vorstellungsgespräch anfordern', max_length=200, verbose_name='Formular / Titel'),
        ),
    ]
