# Generated by Django 2.2.2 on 2019-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190615_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO Einstellung', 'verbose_name_plural': 'SEO Einstellungen'},
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_tag',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
