# Generated by Django 2.2.2 on 2019-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190809_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, help_text='Aktiviert sich wenn diese Url in der Leiste ist.', max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
