# Generated by Django 2.2.2 on 2019-08-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190809_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcode',
            options={'verbose_name': 'Eigener Code', 'verbose_name_plural': 'Eigene Codes'},
        ),
    ]
